baseurl: https://koltluo.github.io/shop/
paginate: 5



enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
hasCJKLanguage: true

services:
   googleAnalytics:
     ID: G-2NPSXGYM2K
module:
  imports:
    - path: github.com/imfing/hextra

    
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

enableInlineShortcodes: true    

outputs:
  home: [HTML,RSS,"JSON"]
  page: [HTML]
  section: [HTML, RSS]

defaultContentLanguage: zh-cn
languages:

  zh-cn:
    languageName: "简体中文"
    weight: 1
    title: 山东临沂森阔机电有限公司 
    description: 山东临沂森阔机电有限公司是一家专业供应变频器、软启动器、软启动柜、高低压成套设备的公司，具备多年的生产和销售经验，提供高质量、高性能的产品，以满足不同客户的需求。我们致力于为客户提供全面的售前、售中、售后服务，欢迎联系我们。热线：15064999739

pagination:
  pagerSize: 12
imaging:
  resampleFilter: "CatmullRom"
  quality: 85
  anchor: "smart"
  resizeMethod: "Lanczos3"
  maxWidth: 1920
  maxHeight: 1080
  formats:
    webp:
      quality: 90
    jpg:
      quality: 85
  exif:
    disableDate: true
    disableOrientation: true

menu:
  main:
    - identifier: doc
      name: 使用手册
      pageRef: /docs
      weight: 1
    - identifier: products
      name: 产品中心
      pageRef: /products
      weight: 2
     
    - identifier: blog
      name: 新闻博客
      pageRef: /blog
      weight: 3    
    - identifier: about
      name: 关于我们
      pageRef: /about
      weight: 4
    - identifier: contact
      name: 联系我们
      pageRef: /contact
      weight: 5     
    - name: 搜索
      weight: 8
      params:
        type: search
    
        

  sidebar:
    - identifier: more
      name: 更多
      params:
        type: separator
      weight: 1
    - identifier: about
      name: "关于我们"
      pageRef: "/about"
      weight: 4
    - identifier: contact
      name: "联系我们"
      pageRef: "/contact/"
      weight: 5 


params:
  
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/logo.png.webp
      dark: images/logo.png.webp
      width: 50
      height: 50
          #link: /
    width: full

  page:
    # full (100%), wide (90rem), normal (1280px)
    width: normal

  theme:
    # light | dark | system
    default: system
    displayToggle: true

  footer:
    enable: true
    displayCopyright: false
    displayPoweredBy: false
    width: normal
    contact:
      address: "山东省临沂市兰山区通达路与清河北路交汇东北角"
      email: "sales@lyskjd.com"
      phone: "+86-150-6499-9739"
      hours: "Monday to Friday: 9:00-18:00"
    company:
      description: "变频器软启动柜厂家主营：高品质在线软启动器，旁路软起动器，在线软启动柜，矢量变频器，变频控制柜，高低压元器件及成套设备，服务全球客户。我们欢迎全球代理商、分销商、零售商以及其他合作伙伴加入我们，共同发展互利共赢的商业关系。"
      name: "临沂森阔机电有限公司"
    icp: 鲁ICP备17034385-2


  displayUpdatedDate: true
  dateFormat: "January 2, 2006"

  # Search
  # flexsearch is enabled by default
  search:
    enable: true
    type: flexsearch

    flexsearch:
      # index page by: content | summary | heading | title
      index: content

  blog:
    list:
      displayTags: true

  comments:
    enable: false
    type: giscus

    # https://giscus.app/
    giscus:
      repo: koltluo/crusher
      repoId: R_kgDOLtH5nw
      category: General
      categoryId: DIC_kwDOLtH5n84Cet-I
      # mapping: pathname
      # strict: 0
      # reactionsEnabled: 1
      # emitMetadata: 0
      # inputPosition: top
      lang: en
      