name = "alipay-worker"
account_id = "230bd2ec354ecc66cdd93a56d8fb07f7"  # Cloudflare 账户 ID
workers_dev = true
compatibility_date = "2025-03-21"

# 指定入口文件
main = "dist/index.js"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "ORDERS"  # Worker 中使用的变量名
id = "c713a9818d7549ebbd8b1ed37c6b76e3"  # KV 命名空间 ID



# 生产环境配置（可选）
[env.production]
name = "alipay-worker-production"
zone_id = "3ad1bcbd10951aca45475cb4eeeefe39"  # 自定义域名的 Zone ID
routes = [
  "shop.lyskjd.com/api/*"  # 自定义路由
]


