name = "alipay-worker"
type = "javascript"
account_id = "230bd2ec354ecc66cdd93a56d8fb07f7"  # Cloudflare 账户 ID
workers_dev = true
compatibility_date = "2025-03-21"

# 指定入口文件
main = "src/index.js"

# 如果需要上传静态资源
[assets]
directory = "./dist"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "ORDERS"  # Worker 中使用的变量名
id = "c713a9818d7549ebbd8b1ed37c6b76e3"  # KV 命名空间 ID

# 环境变量
[vars]
ALIPAY_APP_ID = "@alipayAppId"
ALIPAY_PRIVATE_KEY = "@alipayPrivateKey"
ALIPAY_PUBLIC_KEY = "@alipayPublicKey"

# 生产环境配置（可选）
[env.production]
name = "alipay-worker-production"
zone_id = "3ad1bcbd10951aca45475cb4eeeefe39"  # 自定义域名的 Zone ID
routes = [
  "shop.lyskjd.com/api/*"  # 自定义路由
]


